export const DRAWING_ITEMS = 'drawingItems'
export const DRAWING_ITEMS_VERSION = '1.0.0'
export const DRAWING_ITEMS_VERSION_KEY = 'DRAWING_ITEMS_VERSION'
export const DRAWING_ID = 'idGlobal'
export const TREE_NODE_ID = 'treeNodeId'
export const FORM_CONF = 'formConf'
export const LANG = 'lang'
